<?php
/*
 * implements hook_form_alter()
 **/

 function ajustes_form_alter(&$form, &$form_state, $form_id){
 	if($form_id == 'comment_node_blog_post_form'){
 		$form['author']['name']['#title'] = '';
 		$form['author']['name']['#attributes'] = array('placeholder' => t('Author'));
 		$form['comment_body'][LANGUAGE_NONE][0]['#title'] = '';
 		$form['comment_body'][LANGUAGE_NONE][0]['#attributes'] = array('placeholder' => t('Comment'));
 		$form['field_correo'][LANGUAGE_NONE][0]['email']['#title'] = '';
 		$form['field_correo'][LANGUAGE_NONE][0]['email']['#attributes'] = array('placeholder' => t('Email'));
 	}elseif($form_id == 'commerce_checkout_form_checkout'){
    //var_export($form);
    global $user;
     if( $form_id == 'commerce_checkout_form_checkout' && $user->uid ){
      $user = user_load( $user->uid );
      //var_export( $form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['#address']);
      // For each field in customer profile I fill the form field with the $user value 
      if(isset($user->field_full_name) && !empty($user->field_full_name)){
        $form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['#address']['name_line']  = $user->field_full_name[LANGUAGE_NONE][0]['value'];
        $form['customer_profile_shipping']['commerce_customer_address'][LANGUAGE_NONE][0]['#address']['name_line']  = $user->field_full_name[LANGUAGE_NONE][0]['value'];
      }
      if(isset($user->field_provincia) && !empty($user->field_provincia)){
       $form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['#address']['locality'] = $user->field_provincia[LANGUAGE_NONE][0]['value'];
       $form['customer_profile_shipping']['commerce_customer_address'][LANGUAGE_NONE][0]['#address']['locality'] = $user->field_provincia[LANGUAGE_NONE][0]['value'];
      }
    }
  } /*elseif($form_id == 'views_form_commerce_cart_form_default') {
    dpm($form);
  }*/
   elseif($form_id == 'views_exposed_form'){
      unset($form['#info']['filter-field_product_field_color'], $form['field_product_field_color']);
      //$form['field_product_field_color'] = '';
   }
 }

/**
* Implements hook_form_FORM_ID_alter
*/
function ajustes_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state){
  // Add read only price field to add to cart form
  $form['submit']['#attributes']['value'] = t('Add to');
  $form['submit']['#attributes']['class'] = array('cart-submit');
  if (isset($form_state['default_product']->commerce_price)){
    $price = commerce_product_calculate_sell_price($form_state['default_product']);
    $form['precio_unidad'] = array(
      '#title' => t('Price per unit:'),  
      '#type' => 'item',
      '#markup' => '<div id="monto-precio-unidad" class="monto-precio">' . commerce_currency_format($price['amount'], $price['currency_code']) . '</div>',
      '#prefix' => '<div class="display-price">',
      '#suffix' => '</div>',
      '#weight' => 44,
    );
    $form['precio_preliminar'] = array(
      '#title' => t('Total cost preliminary:'),  
      '#type' => 'item',
      '#markup' => '<div id="monto-precio-preliminar" class="monto-precio">' . commerce_currency_format($price['amount'], $price['currency_code']) . '</div>',
      '#prefix' => '<div class="display-price">',
      '#suffix' => '</div>',
      '#weight' => 46,
    );
    //$form['quantity']['#value'] = 1;
  }
}

/**
 * Implements hook_block_info().
 */
function ajustes_block_info() {
  $blocks['descripcion_categoria'] = array(
    // The name that will appear in the block list.
    'info' => t('Category description'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function  ajustes_block_view($delta = '') {
  switch ($delta) {
    case 'descripcion_categoria':
      $block['subject'] = '';
      if (user_access('access content')) {
        // Use our custom function to retrieve data.
        $result = current_category_description();
        $block['content'] = array(
          '#markup' => current_category_description(),
        );
      }
    return $block;
  } 
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
/*function ajustes_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state, $form_id) {
  $form['submit']['#attributes']['value'] = t('Buy Now');
}*/

/**
 * Custom content function. 
 * 
 * Get product category description
 * 
 * @return 
 *   A result set of the targeted product category.
 */
function current_category_description(){
  //get current taxonomy term id
  $term = taxonomy_term_load(arg(1));
  if($term){
    return '<h2>'.$term->name.'</h2>'.'<div class="ver-mas cerrado"><a href="">'.t('see more').'<span></span></a></div><div id="menu-toggle-wrapper"><a data-status="closed" href="" id="menu-toggle">Menu</a></div><div class="hidden category-description">'.$term->description.'</div>'; 
  }
}