<?php
  /**
   * implements 
   */
function terapias_menu()
{
  $info = array();

    $info['admin/terapias/%'] = array(
        "title" => t('Therapies system'),
        "description" => "",
        "page callback" => 'drupal_get_form',
        'page arguments' => array('terapias_form', 2),
        'access callback' => getCurrentUser(),
        'type' => MENU_CALLBACK
    );
    return $info;
}


/**
 * implements hook_form() 
 */
function terapias_form($form, &$form_state, $id_terapia)
{
	$terapia = '';
	$usuario = '';
	$usuario_id = 0;
	if($id_terapia != 'todos'){
		$terapia = node_load($id_terapia);
		//obtener el usuario asignado a la terapia
		$query = db_select('users', 'u');
		$query->fields('u', array('uid'));
		$query->join('field_data_field_terapias', 'fdft', 'fdft.entity_id = u.uid');
		$query->condition('fdft.field_terapias_target_id', $id_terapia);
		$result = $query->execute();
		while($record = $result->fetchAssoc()){
			$usuario_id = $record['uid'];
		}
	}
	
  $form = array();
  
  $form['form-wrapper-therapy'] = array(
    '#type' => 'fieldset',
    '#title' => t('Add therapy'), 
    '#weight' => 5, 
    '#collapsible' => TRUE, 
    '#collapsed' => FALSE,
		'#prefix' => ($terapia != '') ? '<br /><h2>Terapia: ' . $terapia->title . '</h2><a href="/admin/terapias/todos">Nueva terapia</a><br />' : '',
  );
  
  $form['form-wrapper-therapy']['therapy-id'] = array(
       '#prefix' => '<br/>',
       '#type' => 'select',
       '#title' => t('Name of the therapy'),
       '#options' => getTherapies(),
       '#default_value' => ($terapia != '') ? $terapia->field_tipo_de_terapia[LANGUAGE_NONE][0]['tid'] : 1,
       '#description' => t('Select the name of the therapy.'),
       '#suffix' => '<br/>',
   );
	
	$fecha = date("d-m-Y", time());	
  if($terapia != ''){
		$date = strtotime($terapia->field_fecha_terapia[LANGUAGE_NONE][0]['value']);
		$fecha = date('Y-m-d',$date);
	} 
   $form['form-wrapper-therapy']['date'] = array(
      '#type' => 'date_select',
      '#title' => t('Date'),
      '#default_value' => $fecha,
      '#date_format' => "d-m-Y",
      '#date_year_range' => '-0:+2',
      '#description' => t('Select the date of the therapy.'),
      '#suffix' => '<br/>',
   );
  
  $form['form-wrapper-therapy']['recommendations'] = array(
      '#title' => t('Recommendations and Observations'),
      '#type' => 'textarea',  
      '#description' => t('Recommendations for the therapy'),
      '#default_value' => ($terapia != '') ? $terapia->body[LANGUAGE_NONE][0]['value'] : '',
      '#suffix' => '<br/>',
  );
  
  $options_user = array(
    1=> t('New'),
    2=> t('Existing')
  );
	
	$class_fieldset = ($terapia != '') ? 'disable' : 'active';
	
  $form['form-wrapper-therapy']['user_fieldset'] = array(
      '#title' => t("New User"),
      '#type' => 'fieldset',
      '#prefix' => '<div id="user_ajax_wrapper" class="' . $class_fieldset . '">',
      '#suffix' => '</div>',
      '#collapsible' => TRUE, 
      '#collapsed' => FALSE,
      '#attributes' => array(
        'id' => ($terapia != '') ? 'existing-user' : 'new-user',
      ),
    );
    
  $form['form-wrapper-therapy']['user_fieldset']['user'] = array(
      '#type' => 'radios',
      '#title' => t('User'),
		  '#default_value' => ($terapia != '') ? 2 : 1,
      '#options' => $options_user,
      '#ajax' => array(
        'callback' => 'ajax_user_fieldset_callback',
        'wrapper' => 'user_ajax_wrapper',
      ),
  );
  	
  //extraer los datos de los usuarios
  $url = 'http://lucesycolores.orbelink.com/terapias-usuarios';
  $options = array(
    'method' => 'GET',
    'header' => 'Content-Type: application/json',
  );
  $result = drupal_http_request($url, $options);
  $data = drupal_json_decode($result->data);
	
  $users = array();
  foreach($data as $key => $value){
    foreach($value as $key2 => $value2){
      foreach($value2 as $key3 => $value3){
        $users[$value3['uid']] = $value3['field_full_name'];
      }
    }
  }
  
   $form['form-wrapper-therapy']['user_fieldset']['existing-user'] = array(
    '#title' => t("Existing user email"),
    '#type' => 'select',
    '#options' => $users,
    '#default_value' => $usuario_id,
    '#description' => t(''),
    '#attributes' => array(
      'id' => 'existing-user'
   ),
  );
  
   $form['form-wrapper-therapy']['user_fieldset']['fullname'] = array(
    '#title' => t("Full name"),
    '#type' => 'textfield',
    '#description' => t(''),
    '#attributes' => array(
      'id' => 'full-name-field'
   ),
  );

  $form['form-wrapper-therapy']['user_fieldset']['email'] = array(
    '#title' => t("Email"),
    '#type' => 'textfield',
    '#description' => t(''),
    '#attributes' => array(
      'id' => 'email-field'
   ),
  );
  
	$form['form-wrapper-therapy']['user_fieldset']['telefono'] = array(
    '#title' => t("Phone"),
    '#type' => 'textfield',
    '#description' => t(''),
    '#attributes' => array(
      'id' => 'phone-field'
   ),
	);
	
	$form['form-wrapper-therapy']['user_fieldset']['provincia'] = array(
    '#title' => t("Province"),
    '#type' => 'select',
		'#options' => array(
			'San José' => 'San José',
			'Cartago' => 'Cartago',
			'Heredia' => 'Heredia',
			'Alajuela' => 'Alajuela',
			'Limón' => 'Limón',
			'Puntarenas' => 'Puntarenas',
			'Guanacaste' => 'Guanacaste',
		),
    '#description' => t(''),
    '#attributes' => array(
      'id' => 'province-field'
   ),
  );
	
  //validar select
   
  if((isset($form_state['values']['user'])) && ($form_state['values']['user'] == 1 )) 
  {
    $form['form-wrapper-therapy']['user_fieldset']['#attributes'] = array(
      'id' => "new-user",
    );
    
    $form['form-wrapper-therapy']['user_fieldset']['#title'] = t('New User');
    
  }elseif((isset($form_state['values']['user'])) && ($form_state['values']['user'] == 2 ))
  {
    $form['form-wrapper-therapy']['user_fieldset']['#attributes'] = array(
      'id' => 'existing-user', 
    );
    $form['form-wrapper-therapy']['user_fieldset']['#title'] = t('Existing User');
  }
  
  $form['form-wrapper-therapy']['add-therapy'] = array(
      '#type' => 'submit',  
      '#value' => t('Add'),
      '#suffix' => '<br/>',
  );
  
  $form['#attached']['css'] = array(
    drupal_get_path('module', 'terapias') . '/css/terapias.css',
		//drupal_get_path('module', 'terapias') . '/bootstrap-datepicker/css/bootstrap-datepicker.css',
		//'https://code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css',
  );

  $form['#attached']['js'] = array(
		drupal_get_path('module', 'terapias') . '/js/maskedinput/src/jquery.maskedinput.js',
		//'https://code.jquery.com/jquery-1.12.4.js',
		//drupal_get_path('module', 'terapias') . '/bootstrap-datepicker/js/bootstrap-datepicker.js',
		//'https://code.jquery.com/ui/1.12.0/jquery-ui.js',
		drupal_get_path('module', 'terapias') . '/js/textarea-helper/textarea-helper.js',
    drupal_get_path('module', 'terapias') . '/js/terapias.js',
  );
  
  return $form;
}

/**
 * form validation
 */
function terapias_form_validate($form, &$form_state){
	//exit('test');
}

/**
 * form submition
 */
function terapias_form_submit($form, &$form_state)
{
	$date = new DateTime($form_state['values']['date']);
	$tipo_terapia = $form_state['values']['therapy-id'];
	
	$term = taxonomy_term_load($tipo_terapia);
	$nombreTerapia = $term->name;
	//validar si es una terapia nueva o una existente
	$prefix = $form['form-wrapper-therapy']['user_fieldset']['#prefix'];
	$pos = strpos($prefix, 'disable');
	$idTerapia = 0;
	if($pos === false){
		//activo, es una terapia nueva
		$idTerapia = createTherapy($nombreTerapia, $form_state['values']['recommendations'], $date->format('Y-m-d'), $tipo_terapia);
	}else{
		//desactivado. se desea modificar la terapia
		$idTerapia = arg(2);
		updateTherapy($nombreTerapia, $form_state['values']['recommendations'], $date->format('Y-m-d'), $idTerapia);
	}
	//validar si es un usuario nuevo o existente
	if($form['form-wrapper-therapy']['user_fieldset']['#attributes']['id'] == 'new-user'){
		//crear terapia
		//crear un usuario con los datos obtenidos
		createUser($form_state['values']['fullname'], getRandomCode(), $form_state['values']['email'], $idTerapia, $form_state['values']['telefono'], $form_state['values']['provincia']);
		drupal_set_message(t('the therapy has been created successfully to the client !client', array('!client' => $form_state['values']['fullname']))); 
	} else {
		updateUserTerapy($form_state['values']['existing-user'], $idTerapia);
		drupal_set_message(t('the therapy has been created successfully to the client !client', array('!client' => $form_state['values']['existing-user']))); 
	}
}

/**
 * funciton callback
 */
function ajax_user_fieldset_callback($form, $form_state)
{
  return $form['form-wrapper-therapy']['user_fieldset'];
}

function _terapias_page() 
{
	return theme('terapias_template');
}

/**
 * implements hook_theme()
 */
function terapias_theme()
{
  $module_path = drupal_get_path('module', 'terapias');
	$themes = array (
		'terapias_template' => array(
			'template' => 'terapias-template', // your template file called custompage.tpl.php
      'path' => $module_path.'/templates',
		),
	);
	return $themes;
}


/**
 *  hook_form_alter()
 */
function terapias_form_alter(&$form, &$form_state, $form_id){
	if($form_id == 'views_exposed_form'){
		if ($form['#id'] == 'views-exposed-form-terapias-block') {
			$form['field_fecha_terapia_value']['value']['#date_format'] = 'd-m-Y';
		}
	}
}

/**
 * custom function
 */
function createTherapy($customTitle, $body, $date, $tipo_terapia) 
{
	
	global $user;
	$values = array(
		'type' => 'terapias',
		'uid' => $user->uid,
		'status' => 1,
		'comment' => 1,
		'promote' => 0,
	);
	$entity = entity_create('node', $values);
	$ewrapper = entity_metadata_wrapper('node', $entity);
	$ewrapper->title->set($customTitle);
	$my_body_content = $body;
	$ewrapper->body->set(array('value' => $my_body_content));
	$ewrapper->body->summary->set('');
	$entity->field_fecha_terapia[LANGUAGE_NONE][0] = array(
      'value' => $date,
      'timezone' => 'UTC',
      'timezone_db' => 'UTC',
	);
	$entity->	field_tipo_de_terapia[LANGUAGE_NONE][0] = array(
			'tid' => $tipo_terapia,
	);
	$ewrapper->save();
	return $ewrapper->getIdentifier();
	
}

/**
 * custom function
 */
function updateTherapy($customTitle, $body, $date, $id_terapia) 
{
	$node = node_load($id_terapia); // ...where $nid is the node id
	$node->title = $customTitle;
	$node->body[$node->language][0]['value'] = $body;
	$node->field_fecha_terapia[$node->language][0]['value'] = $date;
	node_save($node);
}

/**
 * custom function
 */
function createUser($name, $pass, $email, $terapiaId, $telefono, $provincia)
{	
	require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');
	$account = new StdClass();
	$account->is_new = TRUE;
	$account->status = TRUE;
	$account->name = $name;
	$account->pass = $pass;
	$account->mail = $email;
	$account->init = $email;
	$account->field_full_name[LANGUAGE_NONE][0]['value'] = $name;
	$account->field_phone[LANGUAGE_NONE][0]['value'] = $telefono;
	$account->field_provincia[LANGUAGE_NONE][0]['value'] = $provincia;
	$account->field_terapias[LANGUAGE_NONE][0]['target_id'] = $terapiaId;
	
	if(user_save($account)){
		//enviar correo al usuario
		$message = t('New account has been created to user: !user, using pass: !pass', array('!user' => $account->mail, '!pass' => $account->pass)); // Body of your email here.
		$params = array(
							 'body' => $message,
							 'subject' => t('New user account'),
							 'headers'=>'simple',
						 );
		$to = $account->mail;
		drupal_mail('contactform', 'send_link', $to, language_default(), $params, 'soporte@orbelink.com', TRUE);
	}
}
/**
 * custom function
 */
function updateUserTerapy($uid, $terapiaId)
{
	$user_fields = user_load($uid);
	$arrayTerapias = $user_fields->field_terapias;
	
	if(!empty($arrayTerapias)){
			array_push($arrayTerapias[LANGUAGE_NONE], array(
								'target_id' => $terapiaId,
							)
						);
	}else{
		
		$arrayTerapias = array(
											'und' => array(
												0 => array(
													'target_id' => $terapiaId,
												),
											),
										);
		
	}
	
	$user_fields->field_terapias = $arrayTerapias;
	return(user_save($user_fields));
}

/**
 * custom function
 */
function getRandomCode()
{
    $an = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-)(.:,;";
    $su = strlen($an) - 1;
    return substr($an, rand(0, $su), 1) .
            substr($an, rand(0, $su), 1) .
            substr($an, rand(0, $su), 1) .
            substr($an, rand(0, $su), 1) .
            substr($an, rand(0, $su), 1) .
            substr($an, rand(0, $su), 1);
}	

/**
 * custom functon
 */
function getTherapies()
{
  //obtener todas las terapias
  $name = 'Terapias';
  $options = array();
  $vocabulary = taxonomy_vocabulary_machine_name_load($name);
  $tree = taxonomy_get_tree($vocabulary->vid);
  foreach ($tree as $term) {
   //echo $term->tid;
    $options[$term->tid] = $term->name;
  }
  return $options;
}

/**
 * custom functon
 */
function getCurrentUser()
{
  global $user;
  $isAdmin = false;
  
  if($user->uid == 1)
    $isAdmin = true;
  
  return $isAdmin;
}